# DICTIONARIES IN PYTHON 

dic = {
    "name": "abubakar",
    "age" : 19,
    "class": "uni",
    "Uni_Name":"ku"
}

print(dic)
print(dic.keys())

# Nested dic in python 

nested_dic = {
    "name": "abubakar",
    "age" :{
        "age_day": "friday",
        "age_month": "april" 
    },
    "class": "uni",
    "Uni_Name":"ku"
}

print(nested_dic)

# Method in dictionaries

# value() method 
# items() method 
# get()  method 
# update() method

# SETS IN PYTHON 


